(()=>{
const coaching={
'Cable lateral raises':[['Shoulders down','Lead with elbows','Stop at shoulders','Control it down'],'Keep your shoulders away from your ears. Lead the raise with your elbows and stop around shoulder height. Lower slowly without letting the stack pull you down.','Side delts','Shrugging or swinging the weight.'],
'Reverse cable fly':[['Chest proud','Arms sweep wide','Shoulders down','Squeeze rear delts'],'Keep your chest tall and shoulders down. Sweep your arms out and slightly back with soft elbows, then control the return.','Rear delts and upper back','Turning it into a row or using momentum.'],
'Cable front raises':[['Ribs down','Soft elbows','Raise to eyes','Control it down'],'Brace your torso with ribs down. Raise with a slight elbow bend to about eye or shoulder level, then lower under control.','Front delts','Leaning back to swing the weight.'],
'Machine shoulder press':[['Ribs down','Shoulders back','Push yourself down','Control the bottom'],'Keep your back supported and ribs stacked. Press while thinking about pushing your body into the seat, then return smoothly to a comfortable depth.','Front and side delts','Arching your back or shrugging.'],
'Chest press':[['Chest proud','Shoulders back','Elbows tucked','Drive through palms'],'Set your shoulder blades against the pad and keep your chest tall. Keep elbows slightly tucked and press smoothly through your palms.','Chest, with triceps assisting','Letting shoulders roll forward.'],
'Biceps curls':[['Elbows pinned','Chest tall','Curl without swinging','Squeeze the top'],'Keep your upper arms still beside your body. Curl by bending only the elbows and squeeze the biceps before lowering slowly.','Biceps','Swinging your torso or moving elbows forward.'],
'Fly machine':[['Chest proud','Shoulders back','Hug the barrel','Control the stretch'],'Keep your shoulder blades supported and use a soft elbow bend. Bring the arms together like hugging a barrel, then open only as far as your shoulders stay comfortable.','Chest','Overstretching or rolling shoulders forward.'],
'Hammer curls':[['Wrists neutral','Elbows pinned','Chest tall','No swinging'],'Keep thumbs up and wrists straight. Hold your upper arms still and curl without using your torso.','Biceps and brachialis/forearms','Swinging or bending the wrists.'],
'Vertical chest press':[['Chest proud','Ribs down','Elbows tucked','Push through palms'],'Sit firmly against the pad with ribs controlled. Keep elbows slightly tucked and press straight through the palms without reaching the shoulders forward.','Chest and triceps','Flaring ribs or rolling shoulders forward.'],
'Biceps curl machine':[['Armpits planted','Elbows stay put','Curl and squeeze','Slow return'],'Keep your upper arms firmly on the pad. Curl through the elbow, squeeze at the top and lower without losing contact.','Biceps','Lifting elbows off the pad.'],
'Cable biceps':[['Elbows pinned','Shoulders down','Curl to chest','Slow return'],'Stand tall with shoulders relaxed. Keep upper arms fixed and curl the handle using the biceps, then fully control the return.','Biceps','Letting elbows drift forward.'],
'Lat pulldown':[['Chest proud','Shoulders down','Elbows to hips','No rocking'],'Start by setting the shoulders down. Keep your chest tall and drive elbows toward your hips while keeping the torso mostly still.','Lats and upper back','Leaning far back and turning it into a row.'],
'Rope triceps pushdown':[['Elbows pinned','Shoulders down','Push through pinkies','Squeeze the bottom'],'Keep elbows glued to your ribs and shoulders relaxed. Extend the elbows, separate the rope slightly at the bottom and fully squeeze the triceps.','Triceps','Letting elbows travel forward or using body weight.'],
'Seated cable row':[['Chest proud','Shoulders down','Elbows drive back','Pull to ribs'],'Sit tall and keep the torso quiet. Drive elbows back toward your lower ribs and briefly squeeze the shoulder blades before a controlled reach.','Lats and mid-back','Rocking backward to move the weight.'],
'Overhead rope extension':[['Elbows narrow','Ribs down','Stretch behind head','Lock it out'],'Brace your core and keep elbows pointing forward. Let the rope travel behind your head for a triceps stretch, then straighten the elbows fully.','Triceps, especially long head','Flaring elbows or arching your back.'],
'ISO lateral row':[['Chest planted','Shoulders down','Elbows to ribs','Squeeze your back'],'Keep your chest firmly supported. Pull elbows down and back toward the lower ribs, squeeze, then return without losing position.','Lats and mid-back','Lifting your chest off the pad.'],
'Reverse-grip triceps pushdown':[['Elbows pinned','Wrists straight','Shoulders down','Lock it out'],'Keep palms up, wrists neutral and elbows fixed beside your ribs. Extend fully without letting the shoulders take over.','Triceps','Elbows drifting forward or wrists folding.'],
'T-bar row':[['Chest proud','Elbows drive back','Pull to ribs','Squeeze your back'],'Keep your torso braced and chest tall. Pull by driving elbows back toward the ribs and squeeze your mid-back before lowering under control.','Lats, rhomboids and mid-back','Jerking the weight with your torso.'],
'Back extension':[['Brace your core','Hinge at hips','Squeeze glutes','Stop at straight'],'Fold at the hips with a neutral spine, then use glutes and hamstrings to return until your body forms a straight line.','Glutes, hamstrings and spinal erectors','Hyperextending your lower back at the top.'],
'Squats':[['Brace hard','Knees track toes','Sit between hips','Push the floor'],'Brace before descending. Let knees track with toes, sit between your hips and drive the floor away as you stand.','Quads and glutes','Knees collapsing inward or losing your brace.'],
'Leg press':[['Back stays planted','Knees track toes','Push whole foot','Control the depth'],'Keep hips and lower back against the pad. Lower only as far as you can stay planted, then push through the whole foot.','Quads and glutes','Letting knees cave in or pelvis curl off the pad.'],
'Single-leg press':[['Hips stay square','Knee tracks toes','Push whole foot','Control the depth'],'Keep both hips square against the pad. Track the working knee over the toes and press through the whole foot without twisting.','Quad and glute of working leg','Hip rotation or knee collapsing inward.'],
'Hamstring curl':[['Hips glued down','Curl your heels','Squeeze hamstrings','Slow return'],'Keep hips pressed into the pad. Curl by pulling your heels toward you, squeeze the hamstrings and lower slowly to full control.','Hamstrings','Lifting hips or bouncing the weight.'],
'Calf raises':[['Drop the heel','Drive through toes','Squeeze the top','No bouncing'],'Use a full comfortable stretch at the bottom, rise through the ball of the foot and pause at the top before lowering slowly.','Calves','Bouncing through the bottom or using partial reps.']
};
function generic(ex){let n=ex.name.toLowerCase();if(/pull.?up|chin.?up/.test(n))return [['Break the bar','Chest proud','Elbows to hips','No swinging'],'Create tension by imagining you are bending the bar apart. Keep your chest tall and drive elbows down toward your hips as you pull.','Lats and upper back, with biceps assisting','Swinging or shrugging into the rep.'];if(/hang/.test(n))return [['Grip the bar','Shoulders gently down','Ribs stacked','Breathe slowly'],'Hold the bar firmly and keep a small amount of shoulder tension instead of collapsing completely into the joints. Keep ribs stacked and breathe.','Grip, forearms and shoulder stabilizers','Shrugging painfully or forcing range.'];return [['Brace your core','Control the rep','Full safe range','Squeeze the target'],`Stay stable and move through a comfortable full range. Keep the rep controlled and focus on the target muscle instead of momentum.`,ex.workout,'Using momentum or losing position.']}
function getCoach(ex){return coaching[ex.name]||generic(ex)}
const style=document.createElement('style');style.textContent='.quick-cues{display:flex;gap:7px;flex-wrap:wrap;margin:12px 0 0}.quick-cue{padding:6px 9px;border-radius:999px;background:var(--panel2);border:1px solid var(--line);font-size:12px;font-weight:800;color:var(--text)}.coach-modal{position:fixed;inset:0;z-index:3000;display:grid;place-items:center;padding:18px;background:rgba(0,0,0,.58);backdrop-filter:blur(5px)}.coach-cloud{width:min(520px,100%);max-height:80vh;overflow:auto;background:var(--panel);border:1px solid var(--line);border-radius:22px;padding:20px;box-shadow:0 24px 70px rgba(0,0,0,.5)}.coach-cloud-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.coach-cloud h2{margin:3px 0 0}.coach-close{width:38px;height:38px;border-radius:50%;background:var(--panel2);color:var(--text);font-size:22px}.coach-detail{margin-top:16px;padding-top:14px;border-top:1px solid var(--line)}.coach-detail strong{color:var(--lime)}.coach-detail p{margin:5px 0 0;line-height:1.5}.coach-label{font-size:11px;text-transform:uppercase;letter-spacing:1px;color:var(--muted);font-weight:800;margin-top:16px}.coach-value{margin-top:5px;line-height:1.5}';document.head.appendChild(style);
window.openCoachDetails=function(name){let ex=exByName(name);if(!ex)return;let [cues,how,feel,avoid]=getCoach(ex),old=document.querySelector('.coach-modal');if(old)old.remove();let modal=document.createElement('div');modal.className='coach-modal';modal.onclick=e=>{if(e.target===modal)modal.remove()};modal.innerHTML=`<div class="coach-cloud" role="dialog" aria-modal="true" aria-label="${name} coaching details"><div class="coach-cloud-head"><div><div class="eyebrow">Exercise details</div><h2>${name}</h2></div><button class="coach-close" aria-label="Close" onclick="this.closest('.coach-modal').remove()">×</button></div>${cues.map(c=>`<div class="coach-detail"><strong>${c}</strong><p>${cueMeaning(c,how)}</p></div>`).join('')}<div class="coach-label">How to perform</div><div class="coach-value">${how}</div><div class="coach-label">You should feel</div><div class="coach-value">${feel}</div><div class="coach-label">Main mistake</div><div class="coach-value">${avoid}</div></div>`;document.body.appendChild(modal)};
function cueMeaning(c,how){let map={'Chest proud':'Keep your chest tall without over-arching your lower back.','Shoulders down':'Keep your shoulders away from your ears and avoid shrugging.','Elbows pinned':'Keep your upper arms fixed beside your ribs throughout the rep.','Elbows drive back':'Think about moving your elbows, not pulling with your hands.','Elbows to hips':'Drive your elbows down toward your hips to recruit the lats.','Push the floor':'Drive your feet into the floor as if pushing it away.','Break the bar':'Imagine bending the bar apart to create lat and upper-back tension.','Ribs down':'Keep your ribcage stacked over your pelvis instead of flaring.','Control it down':'Resist the weight on the return instead of letting it drop.','No swinging':'Keep your torso quiet so the target muscles do the work.','Squeeze the bottom':'Fully straighten the elbows and contract the triceps at the bottom.','Push through pinkies':'Finish the pushdown by separating the rope slightly and emphasizing the outside of the hands.','Knees track toes':'Keep each knee moving in the same direction as the toes.','Brace hard':'Create 360-degree abdominal pressure before you move.','Sit between hips':'Descend between your legs rather than only pushing the hips backward.','Push whole foot':'Keep heel, big toe and little toe loaded as you press.'};return map[c]||how.split('.')[0]+'.'}
const original=window.exerciseCard;window.exerciseCard=function(ex,finished=false){let rec=progression(ex.name,ex.weight,ex.reps,ex.sets),last=logs.find(x=>x.exercise===ex.name),[cues]=getCoach(ex);return `<article class="card exercise"><div class="exercise-head"><div class="exercise-main">${exerciseThumb(ex.name)}<div><div class="eyebrow">${ex.workout}</div><div class="name">${ex.name}</div><div class="meta">Plan: ${ex.sets} sets × ${ex.reps} reps · ${ex.weight||'bodyweight'} ${ex.weight?'lb':''}</div><div class="quick-cues">${cues.map(c=>`<span class="quick-cue">${c}</span>`).join('')}</div></div></div><div class="row"><button class="btn small alt" onclick="openCoachDetails('${esc(ex.name)}')">Details</button>${finished?'<span class="completed-mark">Done ✓</span>':`<button class="btn small" onclick="prefillLog('${esc(ex.name)}')">Start</button>`}</div></div><div class="exercise-body"><div class="recommend">${rec.text}</div>${last?`<p class="cues"><strong>Last workout:</strong> ${formatDate(last.date)} · ${last.sets.map(s=>s.weight+' × '+s.reps).join(' | ')}</p>`:''}<button class="btn small alt" style="margin-top:12px" onclick="editExercise('${esc(ex.name)}')">Edit exercise</button></div></article>`};
if(typeof renderRoutine==='function')renderRoutine();
})();